# First of all you need to set up these variables and tokens in config.yml

token: "yourbottoken"
support_token: "johnsupport" # Support Bot Token
admin_id: "id" # Admin Telegram ID
marz_url: "https://example.com:8000" # Marzban API/Dashboard address
auth_name: "John" # Marzban API login
auth_pass: "Internet" # Marzban API password
crypto: "UQCiOJeH4xC_XtyNcFXNX9MpHxc7NMyD1BkCeKFcBuC9tfVH" # Crypto to support me
crypto_bot_token: "JohnBitcoin" # API token for CryptoBot
stars_price: 150 # Base price of 1-month plan in TG_Stars
crypto_price: 2 # Base price of 1-month plan in USDT
free_traffic: 5 # Traffic limit in Gb for FREE plan
free_days: 30 # Plan limit in Days for FREE plan
language: ru # Language (Available now = [ ru ])

support_bot_id: "@JohnSupport"

uvicorn_host: '0.0.0.0'
uvicorn_port: 1337
crystal_webhook_host: 'http://john.website.ogryn:1337'