FROM python:3.13-alpine AS builder

WORKDIR /usr/src/build

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ python3-dev patchelf \
    && rm -rf /var/lib/apt/lists/* \

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt nuitka
COPY ./app ./app
COPY ./support.py ./support.py
RUN python -m nuitka \
    --standalone \
    --include-package=uvicorn \
    --include-package=fastapi \
    --output-dir=dist \
    support.py

FROM debian:bookworm-slim

WORKDIR /usr/src/app

# Копируем результат компиляции (всю папку .dist)
COPY --from=builder /usr/src/build/dist/support.dist ./dist

# Указываем путь к исполняемому файлу
CMD ["./dist/support.bin"]