FROM python

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY ./support.py ./support.py

CMD ["/bin/bash", "-c", "python support.py"]
