services:
  cheezy-vpn-bot:
    container_name: cheezy-vpn-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./db/db.sqlite3
        target: /usr/src/app/db.sqlite3
      - /var/lib/marzban/certs/:./uvicorn/ssl
    ports:
      - "5000:5000"
    restart: unless-stopped
    tty: true
    stdin_open: true
  cheezy-sup-bot:
    container_name: cheezy-sup-bot
    build:
      context: .
      dockerfile: Dockerfile.sup
    restart: unless-stopped