"""Backwards-compatible re-export of shared ORM models.

The actual models live in `common_db.models` (packages/common_db).
This module exists so legacy imports such as

    from ..database.models import User, SupportTicket

keep working without rewriting every router. New code should import
directly from `common_db.models`.
"""
from common_db import Base  # noqa: F401  (legacy: dashboard code referenced Base)
from common_db.models import (  # noqa: F401
    AndroidFcmToken,
    AppRuntimeSettings,
    BotFeatureFlags,
    CacheVersion,
    CrmCampaign,
    CrmCampaignDelivery,
    CrmEvent,
    CrmEventDelivery,
    CrmWebhookDelivery,
    CrmWebhookRule,
    CreditLedger,
    DashboardBrandingAsset,
    DisabledUser,
    EmailVerification,
    GooglePlayPurchase,
    GooglePlaySku,
    Giveaway,
    GiveawayParticipant,
    GiveawayTicket,
    GiveawayWinner,
    MenuButton,
    MenuScreen,
    MiniappUxEvent,
    PaymentIntegration,
    Promo,
    PromoRedemption,
    PromoSettings,
    PushCampaign,
    PushCampaignDelivery,
    RefreshToken,
    SupportAttachment,
    SupportMessage,
    SupportTicket,
    TelegramLinkCode,
    TelmtFreeParams,
    Transaction,
    User,
    WebAppMenuNode,
)

__all__ = [
    "Base",
    "AndroidFcmToken",
    "AppRuntimeSettings",
    "BotFeatureFlags",
    "CacheVersion",
    "CrmCampaign",
    "CrmCampaignDelivery",
    "CrmEvent",
    "CrmEventDelivery",
    "CrmWebhookDelivery",
    "CrmWebhookRule",
    "CreditLedger",
    "DashboardBrandingAsset",
    "DisabledUser",
    "EmailVerification",
    "GooglePlayPurchase",
    "GooglePlaySku",
    "Giveaway",
    "GiveawayParticipant",
    "GiveawayTicket",
    "GiveawayWinner",
    "MenuButton",
    "MenuScreen",
    "MiniappUxEvent",
    "PaymentIntegration",
    "Promo",
    "PromoRedemption",
    "PromoSettings",
    "PushCampaign",
    "PushCampaignDelivery",
    "RefreshToken",
    "SupportAttachment",
    "SupportMessage",
    "SupportTicket",
    "TelegramLinkCode",
    "TelmtFreeParams",
    "Transaction",
    "User",
    "WebAppMenuNode",
]
