"""Drift guard: catch known inline-query patterns that have a canonical
helper in ``common_db.repo``.

This is the second half of the canonicalisation effort. The first half
(test_no_local_models.py) ensures nobody redefines an ORM class outside
common_db. This file ensures nobody re-introduces a query pattern that
we've already centralised — the kinds of duplication that historically
drifted out of sync across app/, dashboard/, miniapp/ (paid-user
predicate, promo-discount cascade, last-message-per-ticket sub-loop).

The check is intentionally narrow. We do NOT ban all ``select(...)``
calls — joins, aggregations, and pagination still belong in routers.
We only flag patterns that are 1:1 with an existing helper.

When a guard fires, the fix is almost always "import the helper":

    from common_db.repo import users as _repo_users
    user = await _repo_users.get_user_by_tg_id(session, tg_id)

If a new occurrence is *genuinely* outside the helper's contract (e.g.
needs joined data, runs against a different DB), add it to ALLOWED_FILES
below with a comment explaining why.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SCANNED_DIRS = ("app", "dashboard", "miniapp")

# Patterns to flag. Each entry is (regex, why, helper).
INLINE_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    (
        re.compile(r"select\(User\)\.where\(User\.tg_id\s*==\s*[^.]"),
        "single-row user-by-tg_id lookup",
        "common_db.repo.users.get_user_by_tg_id(session, tg_id)",
    ),
    (
        re.compile(
            r'order_status\.in_\(\s*\[\s*["\']confirmed["\']\s*,\s*["\']delivered["\']\s*\]\s*\)'
        ),
        'hardcoded paid-status list ["confirmed", "delivered"]',
        "common_db.repo.users.PAID_ORDER_STATUSES",
    ),
    (
        re.compile(
            r"select\(PromoSettings\)\.where\(PromoSettings\.id\s*==\s*1\)"
        ),
        "raw PromoSettings singleton lookup",
        "common_db.repo.system.get_promo_settings(session)",
    ),
    (
        re.compile(
            r"select\(TelmtFreeParams\)\.where\(TelmtFreeParams\.id\s*==\s*1\)"
        ),
        "raw TelmtFreeParams singleton lookup",
        "common_db.repo.system.get_telmt_free_params(session)",
    ),
]

# Files exempt from the scan. The current refactor leaves a handful of
# legitimate "keep" sites: bulk fetches, complex joins, fuzzy searches.
# Each entry must come with a comment justifying it.
ALLOWED_FILES: frozenset[str] = frozenset({
    # Shim modules re-export models; they reference the names but don't
    # query them.
    "app/database/models.py",
    "dashboard/backend/database/models.py",
    "miniapp/backend/database/models.py",
})


def _python_files() -> list[Path]:
    files: list[Path] = []
    for dirname in SCANNED_DIRS:
        root = REPO_ROOT / dirname
        if not root.exists():
            continue
        for path in root.rglob("*.py"):
            # Skip generated bytecode caches and vendored stuff.
            if "__pycache__" in path.parts:
                continue
            files.append(path)
    return files


def _rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT)).replace("\\", "/")


def test_no_inline_queries_with_canonical_helper() -> None:
    """Each pattern in INLINE_PATTERNS must have zero matches outside
    ``packages/`` and ``ALLOWED_FILES``."""

    violations: list[str] = []

    for path in _python_files():
        rel = _rel(path)
        if rel in ALLOWED_FILES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for pattern, why, helper in INLINE_PATTERNS:
            for m in pattern.finditer(text):
                # 1-based line number for the match start.
                line_no = text[: m.start()].count("\n") + 1
                violations.append(
                    f"{rel}:{line_no}: {why}\n"
                    f"    found: {m.group(0).strip()}\n"
                    f"    use:   {helper}"
                )

    assert not violations, (
        "\n\nInline query patterns found that have a canonical helper in "
        "common_db.repo. Either replace them with the helper or, if the "
        "call site genuinely needs to be a one-off, add the file to "
        "ALLOWED_FILES with a justification comment.\n\n"
        + "\n\n".join(violations)
    )


def test_guard_scans_enough_files() -> None:
    """If somebody changes SCANNED_DIRS by mistake we want a loud failure,
    not a silently-passing guard."""

    files = _python_files()
    assert len(files) >= 50, (
        f"expected to scan at least 50 .py files across {SCANNED_DIRS}; "
        f"got {len(files)}. Did SCANNED_DIRS get truncated?"
    )


def test_guard_actually_fires_on_bait() -> None:
    """Negative test: synthesise a string that matches each pattern and
    verify the regex catches it. Cheap way to make sure a future
    over-clever refactor of the regex doesn't silently become a no-op."""

    bait = [
        ("select(User).where(User.tg_id == 123)",            INLINE_PATTERNS[0][0]),
        ('order_status.in_(["confirmed", "delivered"])',      INLINE_PATTERNS[1][0]),
        ("select(PromoSettings).where(PromoSettings.id == 1)", INLINE_PATTERNS[2][0]),
        ("select(TelmtFreeParams).where(TelmtFreeParams.id == 1)", INLINE_PATTERNS[3][0]),
    ]
    for sample, pattern in bait:
        assert pattern.search(sample), (
            f"regex {pattern.pattern!r} no longer matches its bait "
            f"sample {sample!r} — the guard is broken."
        )
